# Generated by Django 4.1.4 on 2022-12-11 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='countem',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
    ]
