# Generated by Django 4.1.4 on 2022-12-24 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
        ('jobs', '0002_jobs_countem_jobs_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='idemploee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='idemployer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.customuser'),
        ),
        migrations.CreateModel(
            name='sabtjob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_emploee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='main.customuser')),
                ('id_employer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.customuser')),
                ('id_job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.jobs')),
            ],
        ),
    ]
